### ISSUE TITLE
Add modern Rubies to CI (Ruby 3.1, 3.2 and JRuby 9.4)

### ISSUE THREAD

**Issue by petergoldstein** [launchdarkly/ruby-eventsource#38]
Currently the CI doesn't test Ruby 3.1 or 3.2, or JRuby 9.4.  It's also locking bundler to a very old version that may be an issue for more recent Rubies.

Ideally CI should cover all not EOLed Rubies.  I'd be happy to make this change, but because the library is using Circle CI I can't test on a fork.  Just let me know if there's willingness to work on a PR for this and I'll submit an update that we can use as a base.

**Comment by keelerm84** [comment]
Thank you @petergoldstein for raising this issue.

I am in complete agreement as far as adding these new versions to the CI pipeline. If you want to get started on a PR, please feel free. We always welcome external collaboration!

**Comment by petergoldstein** [comment]
@keelerm84 Great.  Just put up #39

**Comment by keelerm84** [comment]
Thanks again for this contribution. I ran it through CI and it looks good so I've gone ahead and merged your PR!
